### ISSUE TITLE
Need to re-build the rpm

### ISSUE THREAD

**Issue by gen1e** [RITlug/tigeros-backgrounds#2]
@Tjzabel or @axk4545  please accept the PR and rebuild the rpm with the new wallpapers, when you get the chance.

**Comment by Tjzabel** [comment]
@gen1e I've merged your PR! One question though after looking through the repository.

I see you've added a tigeros-backgrounds-1.0/ directory, and added new PNG wallpapers within. Would you like these wallpapers to replace the JPG wallpapers found in the base directory?

**Comment by gen1e** [comment]
@Tjzabel Yes those should be replaced, as long as pngs are not a problem. Probably should've been jpgs. I don't know if it makes a difference using the rpm builder. Otherwise I can convert to jpg real quick.

**Comment by Tjzabel** [comment]
@gen1e Okay, just making sure. And no, png's are good. That's the default in `/usr/share/backgrounds/` that Fedora uses.

So, I'll just replace the jpg's with the updated png's and close this issue once it all builds ^>^

**Comment by Tjzabel** [comment]
Rebuild was a success :+1:
